name: extended_text_library
description: package library for extended_text and extended_text_field,provide common base class.
version: 5.0.0-non-null-safety
homepage: https://github.com/fluttercandies/extended_text_library

environment:
  sdk: ">=2.6.0 <2.12.0"
  flutter: "<=1.22.6"
dependencies:
  flutter:
    sdk: flutter

