name: extended_text_library
description: package library for extended_text and extended_text_field,provide common base class.
version: 10.0.0-dev
homepage: https://github.com/fluttercandies/extended_text_library

environment:
  sdk: '>=2.18.0-36.0.dev <3.0.0'
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

